print("Введите первое число")
a = int(input())
print("Введите второе число")
b = int(input())   
print("Сумма равна", a+b)
print("Разность равна", a-b)
print("Произведение", a*b)
print("Частое", a/b)
